### PR TITLE
Updated Constants

### PR DESCRIPTION
**Pull request by holgergrote**
With 2024.1 some Constants got deprecated and needed to be changed to the new definitions

### CODE REVIEW

**Comment by klacol** [comment]
Ok, thanks for you contribution. What is the effect, if we do not change to the new definitions? I am just curious.

**Comment by holgergrote** [comment]
I got warnings in the logs about the constants. It also informs, that these constants will be removed in 2025.1.
So at the moment everything will work. You just get log warnings. It just should be changed till release 2025.1

I do not have the log entries anymore. They look the same like from other integrations.
Example issue with log informations: https://github.com/georgezhao2010/midea_ac_lan/issues/463

I found a blog post about that change:
https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation/

**Comment by klacol** [comment]
Ah, I understand, thanks for this clarification.

**Comment by klacol** [comment]
After merging, i have this error: #15
It maybe related

**Pull request merged**
